spring.application.name=registry
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

management.endpoints.web.exposure.include=health,info

logging.level.root=INFO
logging.level.com.serivce.registry=INFO
logging.level.com.netflix.eureka=INFO
